// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwicygxyhkdgrypqrijo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aWN5Z3h5aGtkZ3J5cHFyaWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Mzk3NjMsImV4cCI6MjA2NjAxNTc2M30.qF68yRU6EDO_gzJ-7qcBlw-Ecj5q8cxaNQZDdYbyprU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});